const datosPrueba = {
    "group": "Grupo C",
    "newStanding": [
    {
    "position": "01",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017942/017942_thumb.png?v=RIw-abjoPUCpC-PZPAcN0ln9ybsA0RkBvaekUd6uvG8",
    "teamName": "Enfurbaos CF",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/8",
    "points": "20",
    "played": "8",
    "won": "6",
    "drawn": "2",
    "lost": "0",
    "goals": "26",
    "goalsAgainst": "14",
    "gd": "+ 12"
    },
    {
    "position": "02",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017930/017930_thumb.png?v=t0UXFMJ0AEWN-rB3s5lPLoKsoVhe3_i9TJK-FNvYC88",
    "teamName": "Aston Birra",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/1",
    "points": "17",
    "played": "8",
    "won": "5",
    "drawn": "2",
    "lost": "1",
    "goals": "33",
    "goalsAgainst": "21",
    "gd": "+ 12"
    },
    {
    "position": "03",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017979/017979_thumb.png?v=a6bhL2sHO12CqA5MePqueVknq-cSp84RUhMUd6d1l_c",
    "teamName": "Texas Guadarrama",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/33",
    "points": "16",
    "played": "8",
    "won": "5",
    "drawn": "1",
    "lost": "2",
    "goals": "32",
    "goalsAgainst": "21",
    "gd": "+ 11"
    },
    {
    "position": "04",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017975/017975_thumb.png?v=DCeTUQO54PPRrklKvJW6RCSQtrkcctLhVghN4xULEws",
    "teamName": "Sansugus FC",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/29",
    "points": "13",
    "played": "8",
    "won": "4",
    "drawn": "1",
    "lost": "3",
    "goals": "30",
    "goalsAgainst": "26",
    "gd": "+ 4"
    },
    {
    "position": "05",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017970/017970_thumb.png?v=GKNRmZvVmAu3075YL1L6Zf1V8EHvhA716NF0XEUfrxw",
    "teamName": "Real Suciedad",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/26",
    "points": "13",
    "played": "8",
    "won": "4",
    "drawn": "1",
    "lost": "3",
    "goals": "24",
    "goalsAgainst": "23",
    "gd": "+ 1"
    },
    {
    "position": "06",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017946/017946_thumb.png?v=dv9VRgP-U-RicCEJqcRaSZjtMrN2MUs9lwwhLuwfnTs",
    "teamName": "Internacionales FC",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/12",
    "points": "12",
    "played": "8",
    "won": "4",
    "drawn": "0",
    "lost": "4",
    "goals": "22",
    "goalsAgainst": "29",
    "gd": "- 7"
    },
    {
    "position": "07",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017950/017950_thumb.png?v=9Qn_AbAfk23AeB-PFKfhTw0Io7k5ELAKsBybkCJUDYE",
    "teamName": "Olimpiakojos FC",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/14",
    "points": "12",
    "played": "8",
    "won": "3",
    "drawn": "3",
    "lost": "2",
    "goals": "25",
    "goalsAgainst": "23",
    "gd": "+ 2"
    },
    {
    "position": "08",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017960/017960_thumb.png?v=QJjBx8mWvQsN0tnS5MbAREKCAevanOl8f34qUXZk1eE",
    "teamName": "Manchester Piti ",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/20",
    "points": "12",
    "played": "8",
    "won": "4",
    "drawn": "0",
    "lost": "4",
    "goals": "21",
    "goalsAgainst": "21",
    "gd": "+ 0"
    },
    {
    "position": "09",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017980/017980_thumb.png?v=b8buxLJinq0D9bB25_I4LbfiSMnsJm53y0sarSmr8xM",
    "teamName": "The Gorronalboys",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/34",
    "points": "11",
    "played": "8",
    "won": "3",
    "drawn": "2",
    "lost": "3",
    "goals": "27",
    "goalsAgainst": "26",
    "gd": "+ 1"
    },
    {
    "position": "10",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017977/017977_thumb.png?v=7tfh92dkDjE8QiOD25AbAIXb1LPs0bvGx9GZFkiKEu4",
    "teamName": "Talleres Pinho",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/31",
    "points": "7",
    "played": "8",
    "won": "2",
    "drawn": "1",
    "lost": "5",
    "goals": "21",
    "goalsAgainst": "23",
    "gd": "- 2"
    },
    {
    "position": "11",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017976/017976_thumb.png?v=UoH3u12ofV_EZffBTELVzYz_TrGM83_0VT9_0KsjfEY",
    "teamName": "Sporting Brugal",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/30",
    "points": "4",
    "played": "8",
    "won": "1",
    "drawn": "1",
    "lost": "6",
    "goals": "32",
    "goalsAgainst": "40",
    "gd": "- 8"
    },
    {
    "position": "12",
    "teamShield": "https://competiciones-moralzarzal.envinya.es/master/teams/017978/017978_thumb.png?v=EdX0Rc5A-s8MNTO9LkGrDiNeq-SmzXtR8UVIbghVNFs",
    "teamName": "Team Perú",
    "link": "https://competiciones-moralzarzal.envinya.es/ligaf7moral/equipo/32",
    "points": "0",
    "played": "8",
    "won": "0",
    "drawn": "0",
    "lost": "8",
    "goals": "14",
    "goalsAgainst": "40",
    "gd": "- 26"
    }
    ]
}

export {
    datosPrueba
}