-- ════════════════════════════════════════════════════════════════════════════
-- SANSUGUS FC · Esquema `sansugus` (comparte el proyecto de Supabase de AITOR FS)
-- Reutiliza public.is_admin() de AITOR FS para las escrituras.
-- No toca el esquema `public`. Se aplicó por partes (tablas, vistas, RLS, permisos, API).
-- Nota: las políticas no son idempotentes; si se repite, borrar antes las existentes.
-- ════════════════════════════════════════════════════════════════════════════

create schema if not exists sansugus;

-- ─── Tablas ─────────────────────────────────────────────────────────────────
create table if not exists sansugus.temporadas (
  id     int generated by default as identity primary key,
  nombre text not null unique,                 -- p. ej. '24/25'
  activa boolean not null default false
);
create unique index if not exists temporadas_una_activa on sansugus.temporadas (activa) where activa;

create table if not exists sansugus.jugadores (
  id             int generated by default as identity primary key,
  nombre         text not null unique,         -- clave usada por las imágenes de la web
  alias          text,
  posicion       text,                         -- posición habitual
  propia_puerta  boolean not null default false -- pseudo-jugador para los goles en propia puerta
);

-- Plantilla de cada temporada (también jugadores sin partidos aún)
create table if not exists sansugus.jugador_temporada (
  jugador_id   int not null references sansugus.jugadores (id) on delete cascade,
  temporada_id int not null references sansugus.temporadas (id) on delete cascade,
  dorsal       int,
  primary key (jugador_id, temporada_id)
);

create table if not exists sansugus.partidos (
  id                 int generated by default as identity primary key, -- 'M.52' del Excel → 52
  local              text not null,
  visitante          text not null,
  fecha              timestamptz,               -- hora de España
  goles_local        int,
  goles_visitante    int,
  penaltis_local     int,                       -- tanda de penaltis ('5 (4)' → 5 y 4)
  penaltis_visitante int,
  campo              int,
  temporada_id       int not null references sansugus.temporadas (id),
  competicion        text not null,
  jornada            text not null,
  jugado             boolean not null default false
);
create index if not exists partidos_temporada_fecha_idx on sansugus.partidos (temporada_id, fecha desc);

create table if not exists sansugus.actas (
  partido_id   int not null references sansugus.partidos (id) on delete cascade,
  jugador_id   int not null references sansugus.jugadores (id),
  titular      boolean not null default false,
  posicion     text,
  goles        int not null default 0 check (goles >= 0),
  asistencias  int not null default 0 check (asistencias >= 0),
  amarillas    int not null default 0 check (amarillas >= 0),
  rojas        int not null default 0 check (rojas >= 0),
  mvp          boolean not null default false,
  dorsal       int,
  primary key (partido_id, jugador_id)
);
create index if not exists actas_jugador_idx on sansugus.actas (jugador_id);

-- Estadísticas de las temporadas anteriores a las actas (21/22 y 22/23)
create table if not exists sansugus.estadisticas_historicas (
  jugador_id   int not null references sansugus.jugadores (id) on delete cascade,
  temporada_id int not null references sansugus.temporadas (id) on delete cascade,
  goles        int not null default 0,
  asistencias  int not null default 0,
  partidos     int not null default 0,
  amarillas    int not null default 0,
  rojas        int not null default 0,
  mvp          int not null default 0,
  primary key (jugador_id, temporada_id)
);

-- ─── Vistas de estadísticas (se calculan desde las actas) ───────────────────
create or replace view sansugus.estadisticas_jugador with (security_invoker = true) as
with agg as (
  select a.jugador_id, p.temporada_id,
         sum(a.goles)::int        as goles,
         sum(a.asistencias)::int  as asistencias,
         count(*) filter (where not j.propia_puerta)::int as partidos,
         sum(a.amarillas)::int    as amarillas,
         sum(a.rojas)::int        as rojas,
         count(*) filter (where a.mvp)::int as mvp
  from sansugus.actas a
  join sansugus.partidos p on p.id = a.partido_id
  join sansugus.jugadores j on j.id = a.jugador_id
  group by a.jugador_id, p.temporada_id
)
select jt.jugador_id, j.nombre as jugador, j.alias, jt.temporada_id, t.nombre as temporada, jt.dorsal,
       coalesce(h.goles,       g.goles,       0) as goles,
       coalesce(h.asistencias, g.asistencias, 0) as asistencias,
       coalesce(h.partidos,    g.partidos,    0) as partidos,
       coalesce(h.amarillas,   g.amarillas,   0) as amarillas,
       coalesce(h.rojas,       g.rojas,       0) as rojas,
       coalesce(h.mvp,         g.mvp,         0) as mvp,
       j.propia_puerta
from sansugus.jugador_temporada jt
join sansugus.jugadores  j on j.id = jt.jugador_id
join sansugus.temporadas t on t.id = jt.temporada_id
left join sansugus.estadisticas_historicas h on h.jugador_id = jt.jugador_id and h.temporada_id = jt.temporada_id
left join agg g on g.jugador_id = jt.jugador_id and g.temporada_id = jt.temporada_id;

create or replace view sansugus.estadisticas_equipo with (security_invoker = true) as
select e.temporada_id, e.temporada,
       sum(e.goles)::int       as goles,
       sum(e.asistencias)::int as asistencias,
       sum(e.amarillas)::int   as amarillas,
       sum(e.rojas)::int       as rojas,
       sum(e.mvp)::int         as mvp,
       (select count(*)::int from sansugus.partidos p
         where p.temporada_id = e.temporada_id and p.jugado
           and p.local <> 'Descansa' and p.visitante <> 'Descansa') as partidos
from sansugus.estadisticas_jugador e
group by e.temporada_id, e.temporada;

-- ─── Seguridad: lectura pública, escritura solo para administradores ────────
alter table sansugus.temporadas enable row level security;
alter table sansugus.jugadores enable row level security;
alter table sansugus.jugador_temporada enable row level security;
alter table sansugus.partidos enable row level security;
alter table sansugus.actas enable row level security;
alter table sansugus.estadisticas_historicas enable row level security;

create policy "lectura publica" on sansugus.temporadas for select to anon, authenticated using (true);
create policy "lectura publica" on sansugus.jugadores for select to anon, authenticated using (true);
create policy "lectura publica" on sansugus.jugador_temporada for select to anon, authenticated using (true);
create policy "lectura publica" on sansugus.partidos for select to anon, authenticated using (true);
create policy "lectura publica" on sansugus.actas for select to anon, authenticated using (true);
create policy "lectura publica" on sansugus.estadisticas_historicas for select to anon, authenticated using (true);

create policy "admins escriben" on sansugus.temporadas for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins escriben" on sansugus.jugadores for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins escriben" on sansugus.jugador_temporada for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins escriben" on sansugus.partidos for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins escriben" on sansugus.actas for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins escriben" on sansugus.estadisticas_historicas for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant usage on schema sansugus to anon, authenticated, service_role;
grant select on all tables in schema sansugus to anon, authenticated;
grant insert, update, delete on all tables in schema sansugus to authenticated;
grant all on all tables in schema sansugus to service_role;
grant usage, select on all sequences in schema sansugus to authenticated, service_role;
alter default privileges in schema sansugus grant select on tables to anon, authenticated;
alter default privileges in schema sansugus grant insert, update, delete on tables to authenticated;
alter default privileges in schema sansugus grant all on tables to service_role;
alter default privileges in schema sansugus grant usage, select on sequences to authenticated, service_role;

-- ─── Exponer el esquema en la API (equivale a API Settings → Exposed schemas) ──
alter role authenticator set pgrst.db_schemas = 'public, graphql_public, sansugus';
notify pgrst, 'reload config';
notify pgrst, 'reload schema';
